# Generated by Django 2.0.1 on 2018-04-22 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='credit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('all_cost', models.IntegerField()),
                ('first_pay', models.IntegerField()),
                ('term', models.IntegerField()),
                ('term_modif', models.CharField(max_length=20)),
                ('percent', models.DecimalField(decimal_places=2, max_digits=14)),
            ],
        ),
        migrations.CreateModel(
            name='pay_graf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('pay_count', models.DecimalField(decimal_places=2, max_digits=14)),
                ('pay_cred', models.DecimalField(decimal_places=2, max_digits=14)),
                ('pay_percent', models.DecimalField(decimal_places=2, max_digits=14)),
                ('all_left', models.DecimalField(decimal_places=2, max_digits=14)),
            ],
        ),
    ]
