# Generated by Django 2.0.1 on 2018-05-10 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_calc', '0002_auto_20180501_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='credit',
            name='creation_date',
            field=models.DateField(blank=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='credit',
            name='cur_left',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14),
            preserve_default=False,
        ),
    ]
