# Generated by Django 2.0.1 on 2018-05-10 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_calc', '0003_auto_20180510_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
