# Generated by Django 2.0.1 on 2018-05-10 11:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('online_calc', '0004_auto_20180510_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
