# Generated by Django 2.0.1 on 2018-05-10 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_calc', '0006_remove_credit_term_modif'),
    ]

    operations = [
        migrations.AddField(
            model_name='credit',
            name='term_modif',
            field=models.CharField(choices=[(1, 'месяцев'), (2, 'лет')], default=1, max_length=20),
        ),
    ]
