# Generated by Django 2.0.1 on 2018-05-10 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_calc', '0007_credit_term_modif'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit',
            name='term_modif',
            field=models.CharField(choices=[(1, 'месяцев'), (2, 'лет')], default=2, max_length=20),
        ),
    ]
